import type { Metadata } from "next";
import "./globals.css";
import { shoulders } from "@/app/fonts"
import Providers from "./providers";


export const metadata: Metadata = {
  title: "Modern Art Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={shoulders.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
